"""init

Revision ID: 52bb9ab9e9b2
Revises: 
Create Date: 2025-11-16 17:26:49.157663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52bb9ab9e9b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tovar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazva', sa.String(length=100), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('tsina', sa.Float(), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tovar')
    op.drop_table('feedback')
    # ### end Alembic commands ###
