"""add image to tovar

Revision ID: 641cc9d7854d
Revises: a84afdd35a84
Create Date: 2025-12-17 14:36:20.505429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641cc9d7854d'
down_revision = 'a84afdd35a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tovar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tovar', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
